import Link from "next/link";
import { Download, Phone, Mail, User, Shield, Eye, Heart, FileText, AlertCircle, ExternalLink, PiggyBank, Coins } from "lucide-react";

interface BenefitCard {
    id: string;
    name: string;
    provider: string;
    icon: React.ReactNode;
    color: string;
    groupId: string;
    customerService: string;
    memberId: string;
    keyPoints: string[];
    appLinks?: {
        ios: string;
        android: string;
    };
    website?: string;
}

interface DownloadableForm {
    id: string;
    title: string;
    filename: string;
    description: string;
}

const BENEFITS: BenefitCard[] = [
    {
        id: "dental",
        name: "Dental Coverage",
        provider: "Altus Dental of RI",
        icon: <Shield className="w-6 h-6" />,
        color: "blue",
        groupId: "6161",
        customerService: "877-223-0588",
        memberId: "Unique ID generated by Altus at enrollment",
        keyPoints: [
            "Download the Altus mobile app for instant access to coverage, claims, and ID cards",
            "At the dentist, provide Group ID 6161, member name and DOB to verify coverage — or the dentist office can call Altus directly",
            "ID cards are printed in member's name only (not issued for spouses or children)",
            "Jasmine Shamer has admin access to Altus and can look up your unique Member ID"
        ],
        appLinks: {
            ios: "https://apps.apple.com/us/search?term=altus%20dental",
            android: "https://play.google.com/store/search?q=altus%20dental&c=apps"
        }
    },
    {
        id: "vision",
        name: "Vision Coverage",
        provider: "Eye Med Vision",
        icon: <Eye className="w-6 h-6" />,
        color: "emerald",
        groupId: "9833526",
        customerService: "866-939-3633",
        memberId: "Your Social Security Number",
        keyPoints: [
            "Download the Eye Med mobile app for ID cards and coverage details",
            "Your Member ID is your SSN",
            "ID cards are printed in member's name only (not issued for spouses or children)",
            "Contact Eye Med directly or Jasmine Shamer for replacement cards"
        ],
        appLinks: {
            ios: "https://apps.apple.com/us/search?term=eyemed%20members",
            android: "https://play.google.com/store/search?q=eyemed&c=apps"
        }
    },
    {
        id: "life",
        name: "Life Insurance",
        provider: "Boston Mutual Life",
        icon: <Heart className="w-6 h-6" />,
        color: "purple",
        groupId: "26734",
        customerService: "877-624-2249",
        memberId: "Policy-based (no ID cards)",
        keyPoints: [
            "$10,000 life insurance policy for active members",
            "No ID cards issued — this is a policy benefit, not a card-based plan",
            "Request proof of your policy from Boston Mutual — Benefit Strategies does not house policy information"
        ]
    },
    {
        id: "retirement",
        name: "Voluntary Retirement (403b)",
        provider: "Fidelity / TIAA",
        icon: <PiggyBank className="w-6 h-6" />,
        color: "emerald",
        groupId: "50266 (Fidelity)",
        customerService: "Online via NetBenefits",
        memberId: "N/A",
        keyPoints: [
            "Contribute to pre-tax or post-tax (Roth) voluntary retirement accounts",
            "Funds are invested with Fidelity or TIAA",
            "Enroll, modify contributions, or schedule appointments online",
            "Fidelity Plan Number: 50266"
        ],
        website: "https://nb.fidelity.com/public/nb/umass/home"
    },
    {
        id: "smart-plan",
        name: "SMART Plan (OBRA)",
        provider: "Empower Retirement",
        icon: <Coins className="w-6 h-6" />,
        color: "amber",
        groupId: "98966-02",
        customerService: "877-457-1900",
        memberId: "N/A",
        keyPoints: [
            "Mandatory for part-time/seasonal/temporary employees (instead of Social Security)",
            "Voluntary contributions available for all employees",
            "Invest pre-tax dollars for retirement savings",
            "Funds managed by Empower Retirement"
        ],
        website: "https://mass-smart.empower-retirement.com/participant/#/login"
    }
];

const DOWNLOADABLE_FORMS: DownloadableForm[] = [
    {
        id: "dental-sbc",
        title: "Dental Summary of Benefits",
        filename: "2018 NEPBA Altus Dental SBC.pdf",
        description: "Altus Dental coverage details and plan information"
    },
    {
        id: "vision-sbc",
        title: "Vision Summary of Benefits",
        filename: "2018 NEPBA Eye Med Vision SBC.pdf",
        description: "Eye Med Vision coverage details and plan information"
    },
    {
        id: "life-form",
        title: "Life Insurance Enrollment",
        filename: "2018 NEPBA Boston Mutual Life Enrollment Form.pdf",
        description: "Boston Mutual Life enrollment and beneficiary form"
    },
    {
        id: "ltd",
        title: "Long Term Disability",
        filename: "Long Term Disability.pdf",
        description: "Long term disability coverage information"
    },
    {
        id: "dues",
        title: "Dues Deduction Form",
        filename: "INTERACTIVE",
        description: "Payroll deduction authorization form for union dues (fillable online)"
    }
];

const colorClasses = {
    blue: {
        bg: "bg-blue-500/10",
        border: "border-blue-500/20",
        text: "text-blue-400",
        hover: "hover:border-blue-500/40"
    },
    emerald: {
        bg: "bg-emerald-500/10",
        border: "border-emerald-500/20",
        text: "text-emerald-400",
        hover: "hover:border-emerald-500/40"
    },
    purple: {
        bg: "bg-purple-500/10",
        border: "border-purple-500/20",
        text: "text-purple-400",
        hover: "hover:border-purple-500/40"
    },
    amber: {
        bg: "bg-amber-500/10",
        border: "border-amber-500/20",
        text: "text-amber-400",
        hover: "hover:border-amber-500/40"
    }
};

export default function BenefitsPage() {
    return (
        <main className="min-h-screen bg-slate-900 text-slate-100 selection:bg-blue-500/30">
            <div className="mx-auto flex min-h-screen max-w-6xl flex-col gap-8 px-4 py-8 md:px-8 md:py-12">

                {/* Header */}
                <header className="flex flex-col gap-4 border-b border-slate-800/60 pb-6 md:flex-row md:items-end md:justify-between animate-fade-in">
                    <div className="space-y-1">
                        <p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-400">
                            NEPBA Local 190
                        </p>
                        <h1 className="text-3xl font-bold text-white tracking-tight">
                            Member Benefits
                        </h1>
                        <p className="text-sm text-slate-400 animate-slide-up delay-100">
                            Your complete guide to NEPBA health, dental, vision, and life insurance benefits.
                        </p>
                    </div>

                    <div className="flex flex-col items-end gap-2 animate-slide-in-left delay-200">
                        <Link
                            href="/dashboard"
                            className="text-xs font-medium text-slate-500 hover:text-blue-400 transition-colors flex items-center gap-1 group"
                        >
                            <span className="group-hover:-translate-x-1 transition-transform">←</span> Back to Dashboard
                        </Link>
                    </div>
                </header>

                {/* Administrator Contact Card */}
                <section className="animate-slide-up delay-100">
                    <div className="relative overflow-hidden rounded-xl border border-amber-600/30 bg-gradient-to-br from-slate-900 to-amber-950/20 p-6 shadow-lg">
                        <div className="absolute top-0 right-0 -mr-8 -mt-8 h-32 w-32 rounded-full bg-amber-500/10 blur-2xl" />

                        <div className="relative z-10">
                            <div className="flex items-center gap-3 mb-4">
                                <div className="h-12 w-12 rounded-xl bg-amber-500/10 flex items-center justify-center text-amber-400 border border-amber-500/20">
                                    <User className="w-6 h-6" />
                                </div>
                                <div>
                                    <h2 className="text-lg font-bold text-white">Benefits Administrator</h2>
                                    <p className="text-sm text-slate-400">Benefit Strategies LLC</p>
                                </div>
                            </div>

                            <div className="grid gap-4 md:grid-cols-3">
                                <div className="flex items-center gap-3 rounded-lg bg-slate-800/50 p-3 border border-slate-700/50">
                                    <User className="w-5 h-5 text-amber-400" />
                                    <div>
                                        <p className="text-xs text-slate-500">Account Executive</p>
                                        <p className="text-sm font-semibold text-white">Jasmine Shamer</p>
                                    </div>
                                </div>
                                <a
                                    href="tel:603-232-8059"
                                    className="flex items-center gap-3 rounded-lg bg-slate-800/50 p-3 border border-slate-700/50 hover:border-amber-500/30 hover:bg-slate-800 transition-all group"
                                >
                                    <Phone className="w-5 h-5 text-amber-400 group-hover:scale-110 transition-transform" />
                                    <div>
                                        <p className="text-xs text-slate-500">Direct Phone</p>
                                        <p className="text-sm font-semibold text-white">603-232-8059</p>
                                    </div>
                                </a>
                                <a
                                    href="mailto:jshamer@benstrat.com"
                                    className="flex items-center gap-3 rounded-lg bg-slate-800/50 p-3 border border-slate-700/50 hover:border-amber-500/30 hover:bg-slate-800 transition-all group"
                                >
                                    <Mail className="w-5 h-5 text-amber-400 group-hover:scale-110 transition-transform" />
                                    <div>
                                        <p className="text-xs text-slate-500">Email</p>
                                        <p className="text-sm font-semibold text-white">jshamer@benstrat.com</p>
                                    </div>
                                </a>
                            </div>

                            <div className="mt-4 flex items-start gap-2 rounded-lg bg-amber-500/5 p-3 border border-amber-500/10">
                                <AlertCircle className="w-4 h-4 text-amber-400 mt-0.5 flex-shrink-0" />
                                <p className="text-xs text-slate-300">
                                    <span className="font-semibold text-amber-400">What Jasmine Can Help With:</span> Replacement ID cards, looking up your Member IDs (she has admin access to Altus Dental's portal), verifying coverage, and answering questions about <span className="font-medium text-white">COBRA</span> and <span className="font-medium text-white">FMLA Direct Billing</span> benefits that Benefit Strategies also administers.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>

                {/* New Officer Notice */}
                <section className="animate-slide-up delay-150 mb-8">
                    <div className="rounded-xl border border-red-500/30 bg-red-950/20 p-6 backdrop-blur-sm">
                        <div className="flex items-start gap-4">
                            <div className="p-3 rounded-xl bg-red-500/10 text-red-400 shrink-0 border border-red-500/20">
                                <AlertCircle className="w-8 h-8" />
                            </div>
                            <div className="space-y-3">
                                <h2 className="text-xl font-bold text-red-100 uppercase tracking-wide">Attention: New Officers</h2>
                                <div className="space-y-2 text-sm text-slate-300 leading-relaxed md:text-base">
                                    <p>
                                        Please fill out the <Link href="/dashboard/forms/dues-deduction" className="text-white underline decoration-red-500/50 hover:decoration-red-500 font-bold hover:text-red-300 transition-colors">NEPBA Dues Deduction Authorization Form</Link> <strong>immediately upon hire</strong>.
                                    </p>
                                    <div className="py-2">
                                        <Link
                                            href="/dashboard/forms/dues-deduction"
                                            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-red-500 hover:bg-red-600 text-white text-sm font-bold transition-colors shadow-lg shadow-red-500/20"
                                        >
                                            <FileText className="w-4 h-4" />
                                            Go to Dues Deduction Form
                                        </Link>
                                    </div>
                                    <p className="font-medium text-white bg-red-500/10 inline-block px-2 py-0.5 rounded border border-red-500/20">
                                        This form must be submitted <span className="text-red-300">prior to the ending date of your first pay period</span>.
                                    </p>
                                    <div className="mt-4 p-4 rounded-lg bg-red-500/10 border border-red-500/20 text-xs text-red-200 md:text-sm">
                                        <p className="font-bold mb-1 flex items-center gap-2">
                                            <Shield className="w-4 h-4" />
                                            REPRESENTATION NOTICE
                                        </p>
                                        <p className="opacity-90">
                                            New hires will only be represented by the union for <strong>bargaining purposes</strong> and <strong className="text-white">not represented for disciplinary purposes</strong> until the officer is off of probation.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Benefit Cards */}
                <section className="grid gap-6 md:grid-cols-3 animate-slide-up delay-200">
                    {BENEFITS.map((benefit) => {
                        const colors = colorClasses[benefit.color as keyof typeof colorClasses];
                        return (
                            <article
                                key={benefit.id}
                                className={`relative overflow-hidden rounded-xl border ${colors.border} ${colors.hover} bg-slate-900/50 p-6 shadow-lg transition-all duration-300 hover:-translate-y-1 hover:shadow-xl`}
                            >
                                <div className={`absolute top-0 right-0 -mr-6 -mt-6 h-24 w-24 rounded-full ${colors.bg} blur-xl`} />

                                <div className="relative z-10">
                                    <div className="flex items-center gap-3 mb-4">
                                        <div className={`h-12 w-12 rounded-xl ${colors.bg} flex items-center justify-center ${colors.text} border ${colors.border}`}>
                                            {benefit.icon}
                                        </div>
                                        <div>
                                            <h3 className="text-lg font-bold text-white">{benefit.name}</h3>
                                            <p className="text-xs text-slate-400">{benefit.provider}</p>
                                        </div>
                                    </div>

                                    <div className="space-y-3 mb-4">
                                        <div className="flex justify-between items-center rounded-lg bg-slate-800/50 p-2.5 border border-slate-700/50">
                                            <span className="text-xs text-slate-400">Group ID</span>
                                            <span className={`text-sm font-bold ${colors.text}`}>{benefit.groupId}</span>
                                        </div>
                                        <a
                                            href={`tel:${benefit.customerService}`}
                                            className="flex justify-between items-center rounded-lg bg-slate-800/50 p-2.5 border border-slate-700/50 hover:border-slate-600 transition-colors"
                                        >
                                            <span className="text-xs text-slate-400">Customer Service</span>
                                            <span className="text-sm font-semibold text-white">{benefit.customerService}</span>
                                        </a>
                                        <div className="rounded-lg bg-slate-800/50 p-2.5 border border-slate-700/50">
                                            <span className="text-xs text-slate-400 block mb-1">Member ID</span>
                                            <span className="text-xs text-slate-200">{benefit.memberId}</span>
                                        </div>
                                    </div>

                                    <div className="border-t border-slate-700/50 pt-4">
                                        <p className={`text-xs font-semibold ${colors.text} mb-2`}>Key Information</p>
                                        <ul className="space-y-2">
                                            {benefit.keyPoints.map((point, idx) => (
                                                <li key={idx} className="flex items-start gap-2 text-xs text-slate-300">
                                                    <span className={`${colors.text} mt-1`}>•</span>
                                                    <span>{point}</span>
                                                </li>
                                            ))}
                                        </ul>
                                    </div>

                                    {/* Website Link */}
                                    {benefit.website && (
                                        <div className="border-t border-slate-700/50 pt-4 mt-4">
                                            <a
                                                href={benefit.website}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className={`flex w-full items-center justify-center gap-2 rounded-lg ${colors.bg} px-4 py-2 text-sm font-semibold ${colors.text} transition-all hover:brightness-110 border ${colors.border}`}
                                            >
                                                <ExternalLink className="w-4 h-4" />
                                                Visit Website / Enroll
                                            </a>
                                        </div>
                                    )}

                                    {/* Mobile App Links */}
                                    {benefit.appLinks && (
                                        <div className="border-t border-slate-700/50 pt-4 mt-4">
                                            <p className={`text-xs font-semibold ${colors.text} mb-3`}>Download the Mobile App</p>
                                            <div className="flex gap-2">
                                                <a
                                                    href={benefit.appLinks.ios}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-lg bg-slate-800 px-3 py-2 text-xs font-medium text-slate-200 transition-all hover:bg-slate-700 hover:text-white border border-slate-700 hover:border-slate-600"
                                                >
                                                    <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                                                        <path d="M18.71 19.5c-.83 1.24-1.71 2.45-3.05 2.47-1.34.03-1.77-.79-3.29-.79-1.53 0-2 .77-3.27.82-1.31.05-2.3-1.32-3.14-2.53C4.25 17 2.94 12.45 4.7 9.39c.87-1.52 2.43-2.48 4.12-2.51 1.28-.02 2.5.87 3.29.87.78 0 2.26-1.07 3.81-.91.65.03 2.47.26 3.64 1.98-.09.06-2.17 1.28-2.15 3.81.03 3.02 2.65 4.03 2.68 4.04-.03.07-.42 1.44-1.38 2.83M13 3.5c.73-.83 1.94-1.46 2.94-1.5.13 1.17-.34 2.35-1.04 3.19-.69.85-1.83 1.51-2.95 1.42-.15-1.15.41-2.35 1.05-3.11z" />
                                                    </svg>
                                                    iOS
                                                </a>
                                                <a
                                                    href={benefit.appLinks.android}
                                                    target="_blank"
                                                    rel="noopener noreferrer"
                                                    className="flex-1 inline-flex items-center justify-center gap-1.5 rounded-lg bg-slate-800 px-3 py-2 text-xs font-medium text-slate-200 transition-all hover:bg-slate-700 hover:text-white border border-slate-700 hover:border-slate-600"
                                                >
                                                    <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                                                        <path d="M17.523 2.062a.5.5 0 0 0-.27.084L4.34 11.054a.5.5 0 0 0 0 .81L17.252 20.77a.5.5 0 0 0 .77-.42V2.567a.5.5 0 0 0-.5-.505zM5.6 11.46l10.4-7.247v14.494z" />
                                                        <path d="M3.3 7.38L1.5 6.27a1.5 1.5 0 0 0-1.5 0 1.5 1.5 0 0 0 0 2.6l1.8 1.1v4.14l-1.8 1.1a1.5 1.5 0 0 0 0 2.6 1.5 1.5 0 0 0 1.5 0l1.8-1.1V7.38z" />
                                                    </svg>
                                                    Android
                                                </a>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </article>
                        );
                    })}
                </section>

                {/* Long Term Disability (LTD) Section */}
                <section className="animate-slide-up delay-250">
                    <div className="rounded-xl border border-amber-500/20 bg-gradient-to-br from-amber-500/5 to-slate-900 p-6 md:p-8">
                        <div className="flex items-center gap-3 mb-6">
                            <div className="h-12 w-12 rounded-lg bg-amber-500/10 flex items-center justify-center text-amber-400 border border-amber-500/20">
                                <Shield className="w-6 h-6" />
                            </div>
                            <div>
                                <h2 className="text-xl font-bold text-white">Long Term Disability (LTD)</h2>
                                <p className="text-xs text-slate-400">MetLife • GIC Plan</p>
                            </div>
                        </div>

                        <p className="text-sm text-slate-300 mb-6 leading-relaxed">
                            LTD insurance is an income replacement program that financially protects you and your family in the event you become disabled and are unable to perform the material and substantial duties of your job.
                        </p>

                        {/* What is it */}
                        <div className="mb-6">
                            <h3 className="text-sm font-bold text-amber-400 mb-3">What is it?</h3>
                            <p className="text-sm text-slate-300 mb-3">
                                Effective July 1, 2021, MetLife is the GIC&apos;s Long Term Disability (LTD) Carrier. If you are unable to work for 90 consecutive days due to illness or injury, this program provides income replacement. Benefits include:
                            </p>
                            <ul className="space-y-2 text-sm text-slate-300">
                                <li className="flex items-start gap-2">
                                    <span className="text-amber-400 mt-1">•</span>
                                    <span>A <strong className="text-white">tax-free benefit of 55%</strong> of your gross monthly salary, up to a maximum of <strong className="text-white">$10,000 per month</strong>, up to age 65</span>
                                </li>
                                <li className="flex items-start gap-2">
                                    <span className="text-amber-400 mt-1">•</span>
                                    <span>A benefit for partial disabilities</span>
                                </li>
                                <li className="flex items-start gap-2">
                                    <span className="text-amber-400 mt-1">•</span>
                                    <span>A 36-month benefit for behavioral health disabilities</span>
                                </li>
                                <li className="flex items-start gap-2">
                                    <span className="text-amber-400 mt-1">•</span>
                                    <span>Rehabilitation and return-to-work assistance</span>
                                </li>
                                <li className="flex items-start gap-2">
                                    <span className="text-amber-400 mt-1">•</span>
                                    <span>A dependent care expense benefit</span>
                                </li>
                                <li className="flex items-start gap-2">
                                    <span className="text-amber-400 mt-1">•</span>
                                    <span>Partial benefits even if receiving other income, with minimum of $100 or 10% of gross monthly benefit</span>
                                </li>
                            </ul>
                        </div>

                        {/* Eligibility and Enrollment */}
                        <div className="mb-6 p-4 rounded-lg bg-slate-800/50 border border-slate-700">
                            <h3 className="text-sm font-bold text-amber-400 mb-3">Eligibility and Enrollment</h3>
                            <p className="text-sm text-slate-300 mb-4">
                                Active state employees who are eligible for GIC benefits are eligible for LTD.
                            </p>
                            <div className="space-y-4">
                                <div>
                                    <p className="text-xs font-bold text-slate-200 mb-1">Current State Employees:</p>
                                    <p className="text-sm text-slate-400">
                                        All eligible employees can apply for LTD coverage during Annual Enrollment, or at any time during the year. You must provide proof of good health for MetLife&apos;s approval to enter the plan.
                                    </p>
                                </div>
                                <div>
                                    <p className="text-xs font-bold text-slate-200 mb-1">New State Employees:</p>
                                    <p className="text-sm text-slate-400">
                                        Eligible employees may enroll in LTD <strong className="text-emerald-400">without providing evidence of good health</strong>.
                                    </p>
                                    <p className="text-xs text-emerald-300 mt-2 bg-emerald-500/10 p-2 rounded border border-emerald-500/20 flex items-center gap-2">
                                        <Shield className="w-4 h-4 shrink-0" />
                                        <strong>Benefit:</strong> If you sign up immediately upon hire, a <strong>medical exam is NOT required</strong>.
                                    </p>
                                </div>
                                <div className="p-3 rounded-lg bg-amber-500/5 border border-amber-500/20">
                                    <p className="text-xs text-amber-300 mb-2">
                                        <strong>⚠️ Login Required:</strong> You must have a GIC account to apply for LTD coverage. If you don&apos;t have an account, register on the GIC website first.
                                    </p>
                                    <div className="flex flex-wrap gap-2">
                                        <a
                                            href="https://www.mass.gov/mygiclink-member-benefits-portal"
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-amber-500/10 border border-amber-500/30 text-amber-400 text-sm font-medium hover:bg-amber-500/20 transition-colors"
                                        >
                                            <ExternalLink className="w-4 h-4" />
                                            Apply / Enroll for LTD
                                        </a>
                                        <a
                                            href="https://mygiclink.my.site.com/"
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-slate-700 border border-slate-600 text-slate-300 text-sm font-medium hover:bg-slate-600 transition-colors"
                                        >
                                            <User className="w-4 h-4" />
                                            Register for GIC Account
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Monthly Rates Table */}
                        <div className="mb-6">
                            <h3 className="text-sm font-bold text-amber-400 mb-3">Monthly Rates (Effective July 1, 2021)</h3>
                            <p className="text-xs text-slate-400 mb-3">Employee Premium Per $100 of Monthly Earnings</p>
                            <div className="overflow-x-auto">
                                <table className="w-full text-sm">
                                    <thead>
                                        <tr className="border-b border-slate-700">
                                            <th className="text-left py-2 text-slate-300 font-semibold">Age</th>
                                            <th className="text-right py-2 text-slate-300 font-semibold">Premium</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-800">
                                        <tr><td className="py-1.5 text-slate-400">Under Age 24</td><td className="text-right text-white">$0.06</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">25 - 29</td><td className="text-right text-white">$0.07</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">30 - 34</td><td className="text-right text-white">$0.11</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">35 - 39</td><td className="text-right text-white">$0.13</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">40 - 44</td><td className="text-right text-white">$0.30</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">45 - 49</td><td className="text-right text-white">$0.40</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">50 - 54</td><td className="text-right text-white">$0.48</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">55 - 59</td><td className="text-right text-white">$0.60</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">60 - 64</td><td className="text-right text-white">$0.58</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">65 - 69</td><td className="text-right text-white">$0.33</td></tr>
                                        <tr><td className="py-1.5 text-slate-400">70 and over</td><td className="text-right text-white">$0.20</td></tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        {/* Contact and Resources */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="p-4 rounded-lg bg-slate-800/50 border border-slate-700">
                                <h4 className="text-xs font-bold text-slate-300 mb-3">MetLife Contact</h4>
                                <div className="space-y-2">
                                    <a href="tel:1-877-355-6277" className="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors">
                                        <Phone className="w-4 h-4" />
                                        1 (877) 355-6277
                                    </a>
                                </div>
                            </div>
                            <div className="p-4 rounded-lg bg-slate-800/50 border border-slate-700">
                                <h4 className="text-xs font-bold text-slate-300 mb-3">Additional Resources</h4>
                                <div className="space-y-2">
                                    <a href="https://www.mass.gov/info-details/long-term-disability-ltd" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors">
                                        <ExternalLink className="w-4 h-4" />
                                        Mass.gov LTD Information
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Downloadable Forms */}
                <section className="animate-slide-up delay-300">
                    <div className="flex items-center gap-3 mb-4">
                        <div className="h-10 w-10 rounded-lg bg-slate-800 flex items-center justify-center text-slate-400 border border-slate-700">
                            <FileText className="w-5 h-5" />
                        </div>
                        <div>
                            <h2 className="text-lg font-bold text-white">Downloadable Forms & Documents</h2>
                            <p className="text-xs text-slate-400">Official NEPBA benefit forms and summaries</p>
                        </div>
                    </div>

                    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                        {DOWNLOADABLE_FORMS.map((form) => {
                            const isInteractive = form.filename === "INTERACTIVE";
                            const href = isInteractive
                                ? `/dashboard/forms/dues-deduction`
                                : `/documents/benefits/${encodeURIComponent(form.filename)}`;

                            if (isInteractive) {
                                return (
                                    <Link
                                        key={form.id}
                                        href={href}
                                        className="group flex items-start gap-4 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4 shadow-sm transition-all hover:border-emerald-500/40 hover:bg-emerald-500/10 hover:shadow-md hover:-translate-y-0.5"
                                    >
                                        <div className="rounded-lg bg-emerald-500/10 p-2.5 text-emerald-400 border border-emerald-500/20 group-hover:bg-emerald-500/20 transition-colors">
                                            <FileText className="w-5 h-5" />
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <h3 className="text-sm font-semibold text-slate-100 group-hover:text-white transition-colors">{form.title}</h3>
                                            <p className="text-xs text-slate-400 mt-1 line-clamp-2">{form.description}</p>
                                        </div>
                                        <div className="flex-shrink-0 self-center">
                                            <div className="rounded-full bg-emerald-600 p-2 text-white transition-all group-hover:bg-emerald-500">
                                                <span className="text-xs font-bold">→</span>
                                            </div>
                                        </div>
                                    </Link>
                                );
                            }

                            return (
                                <a
                                    key={form.id}
                                    href={href}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="group flex items-start gap-4 rounded-xl border border-slate-800 bg-slate-900/50 p-4 shadow-sm transition-all hover:border-slate-700 hover:bg-slate-800/40 hover:shadow-md hover:-translate-y-0.5"
                                >
                                    <div className="rounded-lg bg-red-500/10 p-2.5 text-red-400 border border-red-500/20 group-hover:bg-red-500/20 transition-colors">
                                        <FileText className="w-5 h-5" />
                                    </div>
                                    <div className="flex-1 min-w-0">
                                        <h3 className="text-sm font-semibold text-slate-100 group-hover:text-white transition-colors">{form.title}</h3>
                                        <p className="text-xs text-slate-400 mt-1 line-clamp-2">{form.description}</p>
                                    </div>
                                    <div className="flex-shrink-0 self-center">
                                        <div className="rounded-full bg-slate-800 p-2 text-slate-400 group-hover:bg-blue-600 group-hover:text-white transition-all">
                                            <Download className="w-4 h-4" />
                                        </div>
                                    </div>
                                </a>
                            );
                        })}
                    </div>
                </section>

                {/* Help Section */}
                <section className="animate-slide-up delay-400">
                    <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900/20 p-6 text-center">
                        <h3 className="text-sm font-semibold text-slate-300 mb-2">Need Additional Help?</h3>
                        <p className="text-xs text-slate-500 mb-4">
                            Have questions about your benefits or need assistance with claims?
                        </p>
                        <div className="flex flex-wrap justify-center gap-3">
                            <a
                                href="tel:603-232-8059"
                                className="inline-flex items-center gap-2 rounded-lg bg-slate-800 px-4 py-2 text-xs font-medium text-slate-200 transition-colors hover:bg-slate-700"
                            >
                                <Phone className="w-4 h-4" />
                                Call Jasmine Shamer
                            </a>
                            <Link
                                href="/dashboard/grievances"
                                className="inline-flex items-center gap-2 rounded-lg border border-slate-700 px-4 py-2 text-xs font-medium text-slate-400 transition-colors hover:border-slate-600 hover:text-slate-200"
                            >
                                Contact E-Board
                            </Link>
                        </div>
                    </div>
                </section>

            </div>
        </main>
    );
}
